---
title: "Introduction to R"
author: "Benjamin Wee and Stephanie Hermawan"
date: "09/03/2018"
output: ioslides_presentation
---

## Welcome - Ben

- Who Am I? 2018 CSB graduate, former tutor in statistics and econometrics at Unimelb

- R user for 2 years, self-taught for empirical research and research assistant work. Now a self-processed stats/coding nerd

- Follow me on twitter: @BenwWee

## Welcome - Steph

- Who am I? Also a 2018 grad, doing my first rotation in Telstra Software Engineering Service Assurance & Billing team. Last year I was a 2017 summer vac in Finance Strategy team. 

- I recently graduated UNSW, studying Computer Science & Commerce. I've been using R for about 4 years, in the context of marketing analytics and machine learning in university level courses.

- I don't use twitter ^_^

## What is R and Rstudio?

- R is a free and open source statistical programming language and software environment. 

- Rstudio is an Integrated Development Environment (IDE). It provides an intuitive workspace for working with R.

- R facilitates a complete data analysis workflow from loading/cleaning data to producing publishable and reproducible documents/slides.

- Used by analysts, statisticians and data scientists for data cleaning, manipulation, modelling and visualisation

## What are we learning today?

- Navigating through Rstudio

- Running basic commands and understanding workflow for data driven analysis

- The key goal for today is to get everyone **comfortable** with the Rstudio interface and motivated to learn more about coding! 

- Only a *taste* of what R can do. Packages used are meant to be user-friendly for "non-programmers" and to improve overall efficiency of data wraggling

## Let's start!

>- What is the most important thing to do when learning to code for the first time?

>- Changing the colour scheme so you look cool!

## Conclusion

- Thank you for attending this session! I hope you all had a good time and feel inspired to learn more about R

- Please join our yammer group: R users

* Potential classes:
    - Loading in different types of spreadsheets (loading in data directly from internet)
    - Understanding the principles of 'clean' or 'tidy' data
    - More fun with ggplot2!
    - Use of base R functions for more niche cases (indexing data, conditional statements, booleens)
    

## Learning R independently

- R makes doing easy things in Excel hard but hard things in Excel very easy 

- Excel allows you to have any "data type" (think numbers, characters, etc) and output in any cell. R forces each column to have the same data type. With a constraint, you are forced to pay more attention to what your data is and how you perform analysis

- You will be forced to think more critically about your data. We will sacrifice convenience for precision and efficiency
  
## Learning R independently

- Learning to code is not something you can do by attending many classes (how much did you learn in lecutres?)

- If you intend to learn R for data analysis, you need to have the bigger picture in mind. You will **need** to struggle through lots of errors and frustration to get basic stuff done

- But I believe this investment can add *heaps* of value in the long run and make your analysis more robust (and your charts/graphs prettier)

- My tip is to have a data problem in mind that you can use R to solve. That way you figure out what you don't know and you can structure your learning and start asking the right questions. 

## Very common errors and problems you will deal with

* **Common Errors**
    + Most of the time, these are syntax errors (forgetting a bracket or comma are the biggest culprits)
    + Forgetting to assign variables (check your enviornment)

* **Diagnostics**
    + If you have '+' in your console everytime you try to run code, you forgot to close a bracket. R thinks you are adding inputs into a function.

## Where to go for help
- Google it! 

- Often google will lead you to stack exchange where a lot of people ask the same questions

- Much of the learning process is understanding *how* to google questions. If your question doesn't yield the answer you want, try asking it in a different way, you will eventually come to the solution

- Ask us! :)

## Resources and cheat sheets
- Dplyr cheatsheet: https://www.rstudio.com/wp-content/uploads/2015/02/data-wrangling-cheatsheet.pdf

- ggplot2 cheatsheet: https://www.rstudio.com/wp-content/uploads/2015/03/ggplot2-cheatsheet.pdf

- R styleguide: http://style.tidyverse.org/

## Why can R do for you?

- R can automate and apply functions quickly over many datasets more efficiently than Excel

- Massive library full of packages (add-ons) which contribute to a large huge visualiastion and modelling libraries

- It is *much* easier to reproduce results and debug without having to worry about multiple tabs, linked formulas and stuff breaking

- Scripting allows you to identify where you made mistakes in your process quickly and then re-run your analysis so that everything is updated immediately

- Excel formulas and functions are stored in the same place. This makes it prone to mistakes. Also slow with large datasets

- It is free and you look cool

## Learning curves

```{r echo=FALSE, fig.height=4, message=FALSE, warning=FALSE, paged.print=FALSE}
library(dplyr)
library(ggplot2)
x <- rep(0:100, 2)
R <- 20*(x[1:101])^0.26
excel <- 0.008*(x[102:length(x)]+38)^1.99-10
data <-cbind(as.data.frame(c(rep("R", 101), rep("Excel", 101))), x, as.data.frame(c(R,excel)))
names(data) <- c("Tool", "x", "Difficulty")

data[dim(data)[1]:185, 3] = NA

ggplot(data, aes(x = x, y = Difficulty)) +
  geom_line(aes(colour = Tool)) +
  labs(title = "Difficulty vs complexity tradeoff",
       x = "Complexity") +
  scale_y_continuous(breaks=c(0, 25, 50, 75, 100)) +
  theme_minimal() + theme(panel.grid.minor = element_line(colour="white"))

```

